Add unit test for STATEMENT_UPDATE change type #47
zekimazan/changedistiller pull request #75
Opened 2018-04-01 11:56 UTC by muzafferbugra

2018-04-01 18:11 UTC, zekimazan requested changes
-You should not change AdditionalObjectStateTest.java
-You should add your test files under unittest package with proper name.
-You should add your input files under resources/testdata/src_changetypes

2018-04-01 20:51 UTC, muzafferbugra commented
hocam yarın kaça kadar tamamlayabilirim kaça kadar izin verirsiniz

2018-04-01 21:11 GMT+03:00 Zeki Mazan <notifications@github.com>:

> *@zekimazan* requested changes on this pull request.
>
> -You should not change AdditionalObjectStateTest.java
> -You should add your test files under unittest package with proper name.
> -You should add your input files under resources/testdata/src_changetypes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zekimazan/changedistiller/pull/75#pullrequestreview-108525389>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYTUXbKwS0nbKoqubXwguPCrvMdvr5wFks5tkRhSgaJpZM4TCziA>
> .
>

2018-04-01 20:52 UTC, muzafferbugra commented
çok sıkıştım şuan yarına 2 sınavım vardı hepsi üst üste geldi

2018-04-01 23:51 GMT+03:00 Muzaffer Buğra Çelik <mbcelik123@gmail.com>:

> hocam yarın kaça kadar tamamlayabilirim kaça kadar izin verirsiniz
>
> 2018-04-01 21:11 GMT+03:00 Zeki Mazan <notifications@github.com>:
>
>> *@zekimazan* requested changes on this pull request.
>>
>> -You should not change AdditionalObjectStateTest.java
>> -You should add your test files under unittest package with proper name.
>> -You should add your input files under resources/testdata/src_changetypes
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/zekimazan/changedistiller/pull/75#pullrequestreview-108525389>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AYTUXbKwS0nbKoqubXwguPCrvMdvr5wFks5tkRhSgaJpZM4TCziA>
>> .
>>
>
>

2018-04-02 17:10 UTC, zekimazan requested changes
-You should not change AdditionalObjectStateTest.java

2018-04-02 17:10 UTC, zekimazan commented on src/test/java/ch/uzh/ifi/seal/changedistiller/unittest/StatementUpdateTest.java
> +    public void testRunnerStatementUpdate() {
Your test method should be statementUpdateTest()

2018-04-02 17:39 UTC, muzafferbugra commented
sadece metodun ismi hatalı dimi hocam, çünkü additionalobjectstatetest i
eski haline getirdim, değiştirmedim yani.

2018-04-02 20:10 GMT+03:00 Zeki Mazan <notifications@github.com>:

> *@zekimazan* requested changes on this pull request.
>
> -You should not change AdditionalObjectStateTest.java
> ------------------------------
>
> In src/test/java/ch/uzh/ifi/seal/changedistiller/unittest/
> StatementUpdateTest.java
> <https://github.com/zekimazan/changedistiller/pull/75#discussion_r178592284>
> :
>
> > +
> +import org.junit.Before;
> +import org.junit.Test;
> +
> +import ch.uzh.ifi.seal.changedistiller.model.entities.SourceCodeChange;
> +
> +public class StatementUpdateTest {
> +    List<SourceCodeChange> sourceCodeChangeList;
> +
> +    @Before
> +    public void setUp() {
> +        sourceCodeChangeList = FileDistillerUtil.getChangesFromFile("StatementUpdate_Left.java", "StatementUpdate_Right.java");
> +    }
> +
> +    @Test
> +    public void testRunnerStatementUpdate() {
>
> Your test method should be statementUpdateTest()
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zekimazan/changedistiller/pull/75#pullrequestreview-108672720>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYTUXS4pb_D9l2iMRUK3ugR0eYQiG8qMks5tkluXgaJpZM4TCziA>
> .
>

2018-04-02 20:19 UTC, closed without merging