Final Commits
zekimazan/changedistiller pull request #86
Opened 2018-04-01 21:13 UTC by berk-12

İstediğiniz üzere projeyi sizin reponuzdan fork edip kendi değişikliklerimi commit ettim.

2018-04-01 22:02 UTC, zekimazan requested changes

2018-04-01 22:02 UTC, zekimazan commented on src/test/java/ch/uzh/ifi/seal/changedistiller/unittest/ParentInterfaceDeleteTest.java
> +	public void classRenamingTest() {
Method name should be picked properly. This is not class renaming test.

2018-04-01 22:02 UTC, zekimazan commented on src/test/java/ch/uzh/ifi/seal/changedistiller/unittest/ReturnTypeDeleteTest.java
> +	public void classRenamingTest() {
Method name should be picked properly. This is not class renaming test.

2018-04-02 18:54 UTC, berkbacalan reviewed
Update and fixed some issues

2018-04-02 18:59 UTC, berk-12 commented
Hatalı dosyaları değiştirdim ve method isimlerini düzelttim

2018-04-02 19:22 UTC, zekimazan requested changes
ParentInterfaceDelete and ReturnTypeDelete tests fail.

2022-11-11 14:07 UTC, closed without merging